<?xml version="1.0" encoding="UTF-8"?>
<ProjectsViewInfo>
	<DiagramOpenInfos activeDiagramId="1.EvlAmGAqCmARbi">
		<Info bounds="Re:0.0,0.0,0.0,0.0" diagramId="YXZR8AmGAqCmARRh" maximized="true" offsetX="0" offsetY="0"/>
		<Info bounds="Re:0.0,0.0,0.0,0.0" diagramId="Q_.UlAmGAqCmAQfX" maximized="true" offsetX="0" offsetY="0"/>
		<Info bounds="Re:0.0,0.0,0.0,0.0" diagramId="MHVUlAmGAqCmAQlM" maximized="true" offsetX="0" offsetY="0"/>
		<Info bounds="Re:0.0,0.0,1894.0,880.0" diagramId="1.EvlAmGAqCmARbi" maximized="true" offsetX="0" offsetY="0"/>
	</DiagramOpenInfos>
	<DiagramLastActivated>
		<Diagram id="1.EvlAmGAqCmARbi" time="1718698051619"/>
		<Diagram id="MHVUlAmGAqCmAQlM" time="1718697955068"/>
		<Diagram id="Q_.UlAmGAqCmAQfX" time="1718697901778"/>
		<Diagram id="YXZR8AmGAqCmARRh" time="1718677601613"/>
		<Diagram id="Use Case Statement" time="0"/>
		<Diagram id="Use Case" time="0"/>
		<Diagram id="User Story" time="0"/>
		<Diagram id="Sprint" time="0"/>
		<Diagram id="Agile" time="0"/>
	</DiagramLastActivated>
</ProjectsViewInfo>